### ISSUE TITLE
Missing files after installing with `npm install`

### ISSUE THREAD

**Issue by Sajam** [Fafruch/react-rrule-generator#17]
Hi everyone,

I've just did `npm install --save react-rrule-generator`.

It generates the following `package.json` dependency:
```
"react-rrule-generator": "^0.1.5",
```

Seems like this installation is corrupted by missing some files. After installation, in `node_modules/react-rrule-generator/package.json` there is: `"main": "build/index.js"`, but the `build` folder is missing. This causes package is not working with `webpack` etc.

The temporary fix is to use the following in `package.json` dependencies:
``
"react-rrule-generator": "github:fafruch/react-rrule-generator",
``

Can you please look into it? I bet everyone just do `npm install react-rrule-generator` which is not working well.

Thanks,
Daniel

**Comment by Fafruch** [comment]
Hello, thanks for spotting that. Lib must haven't been used by anybody since realising 0.1.5 version. #20 fixes that, 0.1.7 version will contain fix for this issue
