### ISSUE TITLE
Bootstrap override

### ISSUE THREAD

**Issue by Sajam** [Fafruch/react-rrule-generator#18]
Hi,

This packages overrides my bootstrap (v3) with newer version. It corrupts all styles on my site. I think bootstrap shouldn't be included in this package (user should be able to choose by installing it manually).

Thanks,
Daniel

**Comment by tb** [comment]
@Fafruch  `src/lib/styles/index.css` should not incude `@imports` and should be exported as seperate webpack output (just the `.rrule` classes). User of lib should import like

    @import '~bootstrap/dist/css/bootstrap.css';
    @import '~react-rrule-generator/dist/rrule.css';

**Comment by Fafruch** [comment]
@tb thanks, for your suggestions. 

Check #21
