### ISSUE TITLE
Feature request: hide output

### ISSUE THREAD

**Issue by Sajam** [Fafruch/react-rrule-generator#19]
Hi,

A feature request: it would be great, if there will be **an option to hide the output (raw rrules)**.

I want to use it, as an input in my event creation form, and I don't want to show technical details (rrules) to my users (it's enough I had possibility to capture rrules in onChange event).

Thanks,
Daniel

**Comment by Fafruch** [comment]
This functionality will be included in 0.2.0 version which will be published with #16. 
You'll be able to pass your rrule to the lib and configure it with its forms or use it only as a generator.

**Comment by Fafruch** [comment]
0.2.0 version should be released in a few days.

**Comment by Fafruch** [comment]
RRuleGenerator has just been published as v 1.0.0. It covers what you suggested.
