### ISSUE TITLE
Not able to import the <RRuleGenerator />

### ISSUE THREAD

**Issue by paulocesarpcfj** [Fafruch/react-rrule-generator#22]
Hi! I'm with an error when trying to import the component into my React Project.

When I import the component and try to render it into the page, it throws an error to my component:
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in. Check the render method of 'Scheduler'.`

But when I try to console.log(RRuleGenerator) it sends an empty object, instead the React Component with the proptypes and the other things.

Could you help me with that? I just installed the package and imported as in the documentation.

Thanks.

**Comment by Fafruch** [comment]
My apologies for getting you into trouble. I've indeed published malfunctioning build, the problem was with webpack entry containing CSS path.

For now everything should be working properly, check #23 if you're interested in changes.
Healthy build is available with 1.0.2 version tag.

Cheers

**Comment by paulocesarpcfj** [comment]
Awesome! Thank you!!
