### ISSUE TITLE
Cannot add multiple day for Monthly by day frequency

### ISSUE THREAD

**Issue by j03w** [Fafruch/react-rrule-generator#25]
For example, 1st and 3rd Monday of every month.

`FREQ=MONTHLY;INTERVAL=1;BYDAY=1MO,3MO`

I guess I can somewhat mitigate by using every other Monday instead although that's not quite exactly the same.

Happy to create PR for this but I'll be able to get to it in a couple of week time at best.

**Comment by Fafruch** [comment]
Hello j03w! Firstly, sorry for a late response. I haven't looked there for a long time.

This is possible to achieve, but a lib for multiselect is needed then, for example react-select. However, please tell me if you're still interested in this feature 😉
