### ISSUE TITLE
Day of week selection does not trigger RRule change on Bootstrap v4.1.3

### ISSUE THREAD

**Issue by DivineOmega** [Fafruch/react-rrule-generator#30]
When using this component with the Bootstrap v4.1.3 JavaScript, the day of the week selection for weekly RRules does not trigger the `onChange` callback. This appear to be Bootstrap's JS interfering with the `btn-group` surrounding the day of the week labels and checkboxes. 

Removing the `data-toggle="buttons"` from this (disabling Bootstrap's JS) seems to work around the issue.

**Comment by Fafruch** [comment]
Hello @DivineOmega. Thank you for your commitment. I must admit I couldn't reproduce it locally, however it seems this meta attribute (together with bootstrap's JS) isn't actually needed at all. Please check #31 Pull Request and give me your feedback. This should fix this issue.

Cheers!

**Comment by DivineOmega** [comment]
Hello @Fafruch. Thanks for the quick response!

I do need Bootstrap's JS for unrelated functionality, but it looks like this PR should fix the issue.

**Comment by DivineOmega** [comment]
Thanks for merging the PR.

Would you be able to publish a new version of the package?

**Comment by Fafruch** [comment]
Published as 1.1.0 version. 👍

**Comment by ash123456789** [comment]
On another note, you seem to be missing the `@import '~react-rrule-generator/build/styles.css';` in the build directory as of the the latest version.

**Comment by Fafruch** [comment]
My great apologies. You're 100% right. Build folder was outdated and was missing stylesheet.

Please check v.1.1.1.

**Comment by DivineOmega** [comment]
Thank you @Fafruch. This seems to all be worked now! :slightly_smiling_face:
