### ISSUE TITLE
RRule parsing bug in current git master branch?

### ISSUE THREAD

**Issue by MPursche** [Fafruch/react-rrule-generator#34]
Hello,

I cloned the code from the current `master` branch of the GitHub repository because I wanted to extend the component with translatable labels for different languages. But I can't get the demo to run. I get the following error message on the demo page:
```JavaScript
RangeError: Invalid array length
RepeatYearlyOn
src/lib/components/Repeat/Yearly/On.js:63
  60 |   disabled={!isActive}
  61 |   onChange={numericalFieldHandler(handleChange)}
  62 | >
> 63 |   {[...new Array(daysInMonth)].map((day, i) => (
  64 |     <option key={i} value={i + 1}>{i + 1}</option>
  65 |   ))}
  66 | </select>
```
The `daysInMonth` variable seems to be set to `undefined` because the input rrule is not parsed correctly. The latest version published on npm(1.1.1) does not seem to have this bug. I haven't found any tagged version in this repository so I'm not sure which version on npm corresponds to which revision on GitHub.

Greetings

Marcel

**Comment by MPursche** [comment]
Update:
 
I was able to track down the bug. The issue is in `rrule.js` and not the code of this library. On my system version `2.5.6` was installed by `npm install`. In this newer version `rrulestr()` has a slightly different output. Because of this `computeRRule` fails. A quick workaround is to pin the version of `rrule` for now by changing the package.json:
```json
--- "rrule": "^2.2.0",
+++ "rrule": "~2.2.0",
```

**Comment by MPursche** [comment]
Hello,

Yes, rrule 2.5.6 had some breaking changes that caused fromString to fail.
The version wasn't pinned in the package.json so it was automatically
updated for me, when I installed it on my system. The changes in the pull
request make the code work with newer versions of rrule.

Greetings
Marcel

Am Mo., 22. Okt. 2018 um 01:25 Uhr schrieb Filip Duczymiński <
notifications@github.com>:

**Comment by Fafruch** [comment]
Hello @MPursche,

May I close this issue, as #35 has been merged?

**Comment by MPursche** [comment]
Hello @Fafruch 
Yes, the issue can be closed now.
