### ISSUE TITLE
Implement value and onChange

### ISSUE THREAD

**Issue by tb** [Fafruch/react-rrule-generator#5]
Implement value and onChange like in https://github.com/JedWatson/react-select#usage

When you do it, you can consider i.e. moving react-copy-to-clipboard code out of lib to demo app. After all its the lib user who decides how to use the edited rrule. It can be copied colipboard but can be also stored via API.

**Comment by Fafruch** [comment]
Handling external onChange is now included in #9. 

What about value? How could RRuleComponent have its initial value? Do you mean it's initial RRule in generated RRule window or anything else?
